services:
  qr-generator:
    image: yusufaktog/qr-code:v1.2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - QR_CODE_WIDTH=250
      - QR_CODE_HEIGHT=250